version: "3.4"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - PGDATA=/vm_pg/data
      - POSTGRES_PASSWORD=${SA_PASSWORD:-Auction_PASSWORD123}
      - POSTGRES_USER=auctions-user
      - POSTGRES_DB=auctions
    volumes:
    - './tmp/:/vm_pg/'

  # psql -c 'CREATE DATABASE "auctions";' -U postgres -h 127.0.0.1
  # psql -c "CREATE USER \"auctions-user\" WITH ENCRYPTED PASSWORD 'Auction_PASSWORD123';" -U postgres -h 127.0.0.1
  # psql -c "GRANT ALL PRIVILEGES ON DATABASE \"auctions\" TO \"auctions-user\" ;"  -U postgres -h 127.0.0.1

  app:
    image: wallymathieu/auctions-api-csharp:1.0.0
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      ConnectionStrings__Redis: ${ConnectionStrings__Redis}
      ConnectionStrings__AzureStorage: ${ConnectionStrings__AzureStorage}
    ports:
      - "8083:80"
    depends_on:
      - db
      - azurite
      - redis

  functions:
    image: wallymathieu/auctions-api-functions:latest
    build:
      context: .
      dockerfile: ./src/Auctions.AzureFunctions/Dockerfile
    ports:
      - 8084:80
    environment:
      AzureWebJobsStorage: ${ConnectionStrings__AzureStorage}
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      ConnectionStrings__Redis: ${ConnectionStrings__Redis}
    depends_on:
      - db
      - azurite
      - redis

volumes:
  redis_data:
    driver: local
