version: "3.4"
services:
  app:
    image: wallymathieu/auctions-api-csharp:1.0.0

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      ConnectionStrings__Redis: ${ConnectionStrings__Redis}
      ConnectionStrings__AzureStorage: ${ConnectionStrings__AzureStorage}
    ports:
      - "8083:80"
    depends_on:
      - db
      - azurite
      - redis

  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  functions:
    build:
      context: .
      dockerfile: ./src/Functions/Dockerfile
    ports:
      - 8084:80
    environment:
      AzureWebJobsStorage: ${ConnectionStrings__AzureStorage}
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      ConnectionStrings__Redis: ${ConnectionStrings__Redis}
    depends_on:
      - azurite
volumes:
  redis_data:
    driver: local
